name: Pull request pipeline
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# for security reasons the github actions are pinned to specific SHAs
jobs:
  link_checker:
    name: Link checker
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8
        with:
          # skip the jekyll files under '_includes' directory
          args: >-
            --verbose
            --no-progress
            --max-retries 1
            --retry-wait-time 10
            --exclude-path './_includes/*.html'
            './release/**/*.md'
            './release/*.md'
            './release-es/*.md'
            './release-es/**/*.md'
            '*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  md_linter:
    name: Lint markdown
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          config: '.markdownlint.yaml'
          globs: '*.md'

  check_en_spelling:
    name: Check spelling
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Spell check
        uses: rojopolis/spellcheck-github-actions@e619e00ca22f01ade9d73048dcd6518bedc552f2
        with:
          config_path: .spellcheck.yaml
